FROM rocker/rstudio:4.2.1

RUN apt-get update \
	&& apt-get install -y \
		python-is-python3 \
		python3-pip \
		openjdk-11-jdk \
		libpcre3 \
		libpcre3-dev \
	&& pip install "numpy<1.24.0" \
	&& pip install scipy fastcluster requests

RUN mkdir /home/rstudio/projects \
	&& mkdir /home/rstudio/interpro \
	&& mkdir /home/rstudio/sanz 

RUN R -e "install.packages(c('seqinr', 'shinyFiles', 'DT', 'shinybusy'))"

COPY rstudio_user_file.R /home/rstudio/rstudio_user_file.R

